### PR TITLE
add oauth2 console to portal - #80

### PR DESCRIPTION
**Pull request by dz-1**

### CODE REVIEW

**Comment by Relivian** [comment]
This is awesome. Didn't expect it that far, especially with JWT handling.
Here my feedback that might address work that's still in progress due to my lack of knowledge which features should be fully available when.
My test conditions (all on a local machine):
- the whole oauth2 service (default settings) was up and running (from docker hub)
- PR branch (#81) for portal was checked out, compiled, and running with its defaults
- view was initialized (yarn), compiled and running with defaults

Tests:
- when running it seems I missed some UI configurations to work with local services
- JWT:
  - JWT generation resulted in an endless progress bar (spinning wheel), config issue?
  - wish: formatted fields (as date) may have a placeholder, showing localized format
  - wish: maybe an additional drop down box for more registered claims (including private claims)
- Services:
  - I had different behavior in different network environments: either it showed a 404 for the /oauth2-console/service path OR a "network error" widget that when it's closed opens up the expected and functioning "add service" widget, adding a service then results in a network error
- Users:
  - same behavior as services
- Clients:
  - same behavior as services and users
Token:
  - shows up right away
  - submit results in network error
Key:
  - same behavior as token

Beside that: it's just perfect. The dialogues provide everything I expected, at least as far as I can oversee at this point.
I still have to figure out the reasons for the inconsistent behavior on my systems. Advice is welcome.

**Comment by dz-1** [comment]
@Relivian 
The code here is only the UI part. It relies on light-router for back-end routing. And light-router relies on consul settings in light-oauth2 projects to be done. To make consul work properly, the defect in ConsulRegistry needs to be fixed.

I have my local work-around for these things. But I cannot check in them because they are just work-arounds, not production-ready. 

I can send them to you over the weekend if you need them.

**Comment by stevehu** [comment]
@dz-1 @Relivian I have merged https://github.com/networknt/light-router/pull/39 from @jsu216 to support static IP behind light-router to give users an option beside of Consul. This would significantly reduce the complex structure to deploy light-router for SPA. I will start to write some documents for this use case.

**Comment by Relivian** [comment]
@dz-1 Thank you for the explanation. I still have a steep learning curve with the whole platform. Explanations like yours help a lot, especially what I was still missing to get it running.

@stevehu 
Thank you very much for your effort. I will definitely look at this too, but I am also going to look into Consul and others anyway. The more I learn about this platform, the more everything make sense and comes together to a very consistent and cohesive design.
Your offer is probably a good way to get into the platform doing smaller steps and I really appreciate this.

**Comment by Relivian** [comment]
@stevehu Is it possible to create a small example with all necessary requirements? I am realizing that make too many assumptions and even some reverse engineering ;) 
For the portal I expected to have 
- a running OAuth2 service (with user, client and service registration or is there even a "basic auth" option with login and password only?)
- probably the portal service up and running (since some of the user management is implemented here)
- in case that there's no alternative to event sourcing, that more services are needed (at least eventuate)
- to look into the client registration part a running client with OAuth2 endpoints for authentication code and token
- to look into the service registration a running service
Surprising to me was that you mentioned:
- the router service 
- the registration service (consul)
since I didn't expect them to be needed in this context.
My questions are: 
- What is the minimum requirement (required services to install and run, configurations included) to get the portal with UI running?
- Is there already some step by step documentation/tutorial/podcast to accomplish this?

I am currently following tutorials and examples on the platform and reading third party docs to learn about the techniques you're using for larger apps, but I still have a hard time to put these fragments together because of some missing links as described above.
What's your recommendation for me?

**Pull request merged**
