### PR TITLE
fixes #90 update webconsole.js for viewer/editor PropTypes to func

### LINKED ISSUE #90: update webconsole.js for viewer/editor PropTypes to func
This is to avoid a warning message in the Javascript console.

### PR DESCRIPTION
**Pull request by stevehu**

### CODE REVIEW

**Comment by dz-1** [comment]
viewer and editor are supposed to be components. I am not sure whether the 'func' type works or not.

**Comment by stevehu** [comment]
@dz-1 I didn't look into the details yet but just made the change according to the warning message. After the change, the warning message is gone. 

I have just published a tutorial on how to set up local router and oauth2 instances with Consul for the UI https://doc.networknt.com/tutorial/portal/local-router/

Most steps are based on your instructions on the slack. Please review and let me know if anything is missing.

**Comment by stevehu** [comment]
@dz-1 Thanks for the review of the tutorial. I will walk through that again to make sure all covered. 

Regarding the warning message. The following is captured on my Javascript console. 

```
Warning: Failed prop type: Invalid prop `viewer` of type `function` supplied to `WebConsole`, expected `object`.
    in WebConsole (created by WithStyles(WebConsole))
    in WithStyles(WebConsole) (at App.js:33)
    in Route (at App.js:30)
    in Switch (at App.js:15)
    in main (at ResponsiveDrawer.js:140)
    in div (at ResponsiveDrawer.js:92)
    in ResponsiveDrawer (created by WithStyles(ResponsiveDrawer))
    in WithStyles(ResponsiveDrawer) (created by Route)
    in Route (created by withRouter(WithStyles(ResponsiveDrawer)))
    in withRouter(WithStyles(ResponsiveDrawer)) (at App.js:14)
    in App (at src/index.js:27)
    in MuiThemeProviderOld (at src/index.js:26)
    in Provider (at src/index.js:25)
    in Router (created by HashRouter)
    in HashRouter (at src/index.js:24)
```

**Comment by dz-1** [comment]
@stevehu ok, I'll check.

**Comment by dz-1** [comment]
@stevehu fixed the type. The `func` types come from functional components.

**Comment by stevehu** [comment]
@dz-1 I have added two entries in the index.md for the local light-portal build with light-bot and local light-portal services deployment. Also, you can find the following link with updated consul.yml, service.yml, and pathPrefixService.yml 

https://github.com/networknt/light-config-test/tree/master/light-router/local-portal/config

**Pull request merged**
